### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by EZarnosky** [JasonHHouse/gaps#117]
**Is your feature request related to a problem? Please describe.**
Yes, kind of

**Describe the solution you'd like**
User Authentication into Gaps.

**Describe alternatives you've considered**
Not many alternatives

**Additional context**
I find it an issue to leave Gaps running when anyone can access the page and get my Plex Token and TMDB API key.

**Comment by JasonHHouse** [comment]
Try testing out the ssl or no ssl version to use the login. It auto-generates a unique password in the log file. Username is 'user'. 
`docker pull housewrecker/gaps:v0.4.0-SNAPSHOT-no-ssl`
`docker pull housewrecker/gaps:v0.4.0-SNAPSHOT`

**Comment by JasonHHouse** [comment]
Enabled in v0.4.0, set a flag in docker run ENABLE_LOGIN=true

**Comment by ssiddiqui87** [comment]
When login is enabled, Radarr is unable to connect to the RSS list. Is there a way to have authentication enabled and maintain Radarr's ability to connect to the list?

**Comment by JasonHHouse** [comment]
What version are you using? Are you running Docker? I haven't seen this before so it would be a new bug.

**Comment by ssiddiqui87** [comment]
I am on version 0.8.10 in Docker. 

Here's what happens if you would like to reproduce the issue. When I try to navigate to my RSS URL (http://<myip>/rss/<rssid>/1) when ENABLE_LOGIN is set to true, it redirects me to the login page. As a workaround, I set this to false, let Radarr update the list, then set it back to True once a week however if I can leave the login enabled and have Radarr still connect, that would of course be ideal.

**Comment by JasonHHouse** [comment]
That makes sense. I'm pretty sure I know why that is happening. I'll take a look into it and keep you posted. Thanks for the bug report.

**Comment by ssiddiqui87** [comment]
Thank you! Just out of curiosity, should I make a new bug report for this since this one we're commenting on is marked as closed?

**Comment by JasonHHouse** [comment]
Yes, please.
