### ISSUE TITLE
FR Native Linux Dockerless Install

### ISSUE THREAD

**Issue by bakerboy448** [JasonHHouse/gaps#182]
Binaries for native linux install

**Comment by JasonHHouse** [comment]
What are you expecting? What Linux binary are you asking for?

**Comment by bakerboy448** [comment]
a simple tarball to download/extract and then run.

that would give 3 options: windows, docker, and linux

similar to the radarr/sonarr installs

**Comment by JasonHHouse** [comment]
Gaps already has that equivalent. Check the zip in the release. https://github.com/JasonHHouse/gaps/releases/download/v0.8.0/Gaps-0.8.0.zip Just running the jar will work. I'm looking into deb packages as well.

**Comment by bakerboy448** [comment]
technically not correct.  if it was the equivalent, it would be untar and run.

this requires unzipping and setting the jar to -x

also full disclosure it needs to be started with `java -jar gaps.jar` which is not intuitive to folks not completely familiar with linux.

it looks like it assumes /usr/data will always exist and if it does not, well I'm getting a ton of errors trying to start it on Whatbox (shared seedbox) https://pastebin.com/t1DyLYuw

**Comment by vanman69ny** [comment]
I would appreciate being able to install it in a jail on truenas/freenas , which uses FreeBSD. 

Thanks

**Comment by bakerboy448** [comment]
```
2020-10-06 02:53:22.145  INFO 17035 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariP                                                                                 ool-1 - Starting...
2020-10-06 02:53:23.146 ERROR 17035 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariP                                                                                 ool-1 - Exception during pool initialization.

java.sql.SQLException: path to '/usr/data/gaps.db': '/usr/data' does not exist

```
getting the following errors when starting...I tried data=/good/path and -data=/good/path

Can/How do we redirect the data path?

**Comment by JasonHHouse** [comment]
That would be a code change.

**Comment by munkee** [comment]
Here's what I did to almost succeed at running it outside of docker:

1. `git clone` the source
2. Change 2 instances of /usr/data to something like /home/USERNAME/gaps in 'GapsWeb/src/main/resources/application.yaml'
3. Install Maven
3. Attempt to `mvn package`
4. Read lots of maven documentation
3. Edit the GapsWeb/pom.xml, RadarrV3/pom.xml files so that the dependencies resolve correctly
4. `mvn package` 
5. Run as `java -jar -Dspring.profiles.active=no-ssl-no-login GapsWeb-0.8.x.jar`

This got me a webapp that I could connect to and it looks right but it wouldn't save the things that I put into the configuration wizard, so I'm not quite there. Eventually I gave up and build a VM with docker even though I'd rather have everything like this running as a separate proxmox container.

**Comment by JasonHHouse** [comment]
I have a better solution. Can you follow the steps in this wiki and let me know?

https://github.com/JasonHHouse/gaps/wiki/Running-in-Linux-Mac-without-Docker

**Comment by JasonHHouse** [comment]
I removed the gaps.db so you shouldn't need that anymore if you check for the latest yml it should be working for you now. https://github.com/JasonHHouse/gaps/blob/master/application-custom.yml

**Comment by Tippon** [comment]
Thank you @JasonHHouse 😃 

Gaps now runs when I use the startOnLinuxAndMac.sh script.

I'm still stuck on the 'create the file: org.user.gaps.plist' section, possibly as I'm running Linux on a PC, and not using a Mac? (I'm in a little bit over my head, but trying to learn). Is there anything that I need to add in from that section, or will I be ok running Gaps from the script as and when I need to?

Thanks again for your help 👍

**Comment by JasonHHouse** [comment]
> create the file: org.user.gaps.plist

I'm not sure what that is. Where are you seeing that?

**Comment by Tippon** [comment]
Sorry, it's from the instructions here:

[https://github.com/JasonHHouse/gaps/wiki/Running-in-Linux-Mac-without-Docker](https://github.com/JasonHHouse/gaps/wiki/Running-in-Linux-Mac-without-Docker)

I've edited the application-custom.yml file to add a folder that Gaps can access, but the next steps appear to be for Mac.

I've got Gaps running using the script, but now I'm running into a similar error to [#247 ](https://github.com/JasonHHouse/gaps/issues/247). I'm still working on it though :)

**Comment by Tippon** [comment]
> but now I'm running into a similar error to #247 . I'm still working on it though :)

Gaps was giving the error:

`2022-01-06 22:35:16.066 ERROR 180541 --- [           main] c.j.gaps.service.FileIoService           : Can't create file /usr/data/gaps.properties

java.io.IOException: No such file or directory
`

but creating a symlink to a writeable folder solved it.

**Comment by JasonHHouse** [comment]
> I've edited the application-custom.yml file to add a folder that Gaps can access, but the next steps appear to be for Mac.

Good point, I should break those apart. The last part is for Mac for sure.

Were you able to get it working now? If you're on Linux, I recommend using Docker as you'll get updates much easier.

**Comment by JasonHHouse** [comment]
> Can't create file /usr/data/gaps.properties

**Comment by Tippon** [comment]
> Were you able to get it working now? If you're on Linux, I recommend using Docker as you'll get updates much easier.

I was, yes. It's running now, and I'm trying it out to see what I'm missing 😃 

I should switch to Docker, but I just couldn't get to grips with it last time I tried. I might try again though so that I'm not missing out.


> > Can't create file /usr/data/gaps.properties
> 
> In the application-custom.yml, there is a storageFolder. Did you update that with a new folder and still see the issue of /usr/data as the specified folder? If so, I'll need to fix that as it should be pulling from the custom yml file.

I did, yes. I changed it to /mnt/films/gaps/ where gaps is a subfolder of my movies collections folder. I changed the properties so that root, media (my user), and everyone, had read/write permissions. I added everyone after it didn't work the first time. 

I've added a symlink from /usr/data/ to /mnt/films/gaps/data/ and that's let it work. It's got the advantage of making the folder easier to access too, so that could be handy in the future, if I need to clear it out for a reinstall, for example.

The contents of my application-custom.yml are below, in case I've got something wrong 👍 

`logging:
  level:
    root: INFO
spring:
  profiles: custom
  mvc:
    async:
      request-timeout: -1
  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true
        cache-public: true
server:
  http2:
    enabled: true
  port: 8484
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  error:
    whitelabel:
      enabled: false
info:
  app:
    name: Gaps
    description: Gaps searches through your Plex Server or local folders for all movies, then queries for known movies in the same collection. If those movies don't exist in your library, Gaps will recommend getting those movies, legally of course.
    version: 0.9.12
    storageFolder: /mnt/films/gaps/ #Change to folder that gaps has permission to read, write, and delete in.
    properties:
      rssFeed: rssFeed.json
      gapsProperties: gaps.properties
      movieIds: movieIds.json
      ownedMovies: ownedMovies.json
      recommendedMovies: recommendedMovies.json
    loginEnabled: false
    sslEnabled: false`

**Comment by JasonHHouse** [comment]
I made a change to the startup script for Mac and Linux. Instead of needing the YML to set the storage folder, it will use $PWD for default location and has the ability to be set with a flag. If you want to try this out I've uploaded the file [here](https://raw.githubusercontent.com/JasonHHouse/gaps/b9324a09e4eedc692e0b79d7e72f087d1f0a9e67/startOnLinuxAndMac.sh).  `./startOnLinuxAndMac.sh -h` for help on the flags.

**Comment by Tippon** [comment]
I've just tried the new script, and it's working perfectly.

I unlinked the /usr/data/ folder from /mnt/films/gaps/data/ just to be sure, and Gaps gave the warning that it couldn't find gaps.properties, but then let me enter my details and saved them.

Everything seems to be working the way that it should.

Thank you for your help, and this fantastic tool 😄

**Comment by JasonHHouse** [comment]
Awesome, I'm glad it works and happy you like it!
